language: node_js
node_js:
- stable
dist: trusty
addons:
  chrome: stable
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_deploy:
- npm run minify
deploy:
- provider: npm
  email: nathan@nfriedly.com
  api_key:
    secure: zpnuGBt/qysRADSRl+tl6pCE5WVECJwT9QOABAGMVLzIu5bAZvjce1jlXsFzmywFrLPXtX8uyUpp2Rt2zY6I9nUOLbYqnDZ6xC3z0o9eR5cc8x4M4GS3RYAwdMp5Pj7TbPnKLU8Vy8B1jhfRatdCGDou7R4/wnZD9INpoW7ZTzBrQun3go++C2+qtdVftqmVcj5Rr78OcPTZYIhsjQrpx2lEQaoHgr00rbUf4L+4ZGOmPcRJuMXkOjdyP73Cg8PQ84OCY0/+5vUo1m8Q6+bQemeFRC/AbkhBEI7H6GTKP1Bukm62JBxfn3R/BzSxbx/riW5OdNa7lCxY49p45mfOLDWguGwL5vnQWHoXI3G7yDiE3rf678OSrsbKePO7QsN4Vluz6zTuetqv/jkf3Q+OCuGwIpWCkzW9ay/z/AHtxgLHgtRrXrBXqgvxLeIvL1lbxoXeNSw/+uB9Xn3i+nFWMPeVN7npXJrWzhTbUZxSggoc3uvLQj9DSrkb88XHpRabyo98MgdPvNBtAH/3EV8xFGXURr6uAkQ32NrUD4sMxPiHHOjdFzRtTqTh3ttvsAKP6hH7z+PV6iWpmb8FX0BebCckf0qMcEb0eP2gGznT049OvcOBsJ6MQ2koneDauYc4WVv3TdSVWsgJXJfyWXWELAeh0f1PHVZQgvWFZGpAWSw=
  on:
    tags: true
    repo: nfriedly/get-user-media-promise
- provider: releases
  api_key:
    secure: bDyEdtdEs5rjz0YJeBbfCqJc2QGHzSRJLp+o0/i7XsarHeC5Bx840MGwnyykVxQLxz8FpxEKKpURcNj/wBAqoYECKy8xeb7Bemz+5UZ/DG9Aviq2yXEzDjKI9yRL5/NJUZe2MYsaHsqZlZdv0ZMzERoN7EYaAHnjwBzuJXb73C2kqPIn/uWjXRaF5RHDLtaNa8DqAH2V7HVH8WbX31yf0QQJxp/sjo1CiXUYj8c5zkN033p3IKPynEW/ueinZYcQVZEG+OoX5IN9nZ2c3dQuxqf41PT8Lqkg5vu7N5l3jTNv6PNgPBkSn7K6Ma3PoBEO9XNvUJeBbjbyg1ytSHUs4pa4hXzeuiE0etYojcWlKcVM8S+a7bzqsLAImhyuze+cNjNQHxhBVWASkAjYKsUvW5nhvQI74wwVw7eoMVxpVNiBEOxbfEK9JxieYuFxauSGc79/EOEYv4jGqksyAEfDx63VNdJ5KCwSc3/XeEggaVu9LL6qYSKff2TQb2lN3gZIrJTLhLAm5jiSpYmGq1jg4xmPVgH9yyLBcf+5fqLzgWvPSFSvCB6iV0vGCBeTnt6Qf6OF78emHxxfwOWlaTWqg4cxfZcKkSzceFGhIEwX8dztWbsEuUrOqHIxGvN6AdWoHELQTpuRgKMn+CmiHZebe/Rr5n/czwJMTXjD/5OiVy8=
  file:
  - lib/get-user-media-promise.js
  - dist/get-user-media-promise.min.js
  skip_cleanup: true
  on:
    tags: true
    repo: nfriedly/get-user-media-promise
